'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const memory={get(k,d=''){try{return localStorage.getItem('cz-'+k)||d}catch{return d}},set(k,v){try{localStorage.setItem('cz-'+k,v)}catch{}}};
let branch=memory.get('branch','city'),pageKey='',lastDay=TRIP.today||'day3',toastTimer;
if(!['city','island'].includes(branch))branch='city';
const activeDays=TRIP.metadata?.navDays||['day3','day4','day5'];
const imageTitles={...(TRIP.archiveImages||{}),...TRIP.images};
function dayData(key){return TRIP.days[key+(['day4','day5'].includes(key)?branch:'')]||TRIP.days[key]}
function dayName(key){return key==='day3'?'汕头 · 安顿':key==='day4'?'市区 / 南澳':'回番禺'}
$('#day-nav').innerHTML=activeDays.map(k=>`<a href="#${k}" data-day="${k}"><b>10.${k.slice(-1)}</b>${dayName(k)}</a>`).join('')+'<a href="#history" class="history-nav" data-day="history"><b>已走</b>10.1–2</a>';
document.body.classList.toggle('large-text',memory.get('large')==='1');
$('#font-toggle').setAttribute('aria-pressed',String(document.body.classList.contains('large-text')));
function toast(s){clearTimeout(toastTimer);$('#toast').textContent=s;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
async function copy(s){try{await navigator.clipboard.writeText(s);toast('已复制')}catch{const ta=document.createElement('textarea');ta.value=s;ta.style.cssText='position:fixed;left:0;top:0;opacity:0';document.body.append(ta);ta.select();let ok=false;try{ok=document.execCommand('copy')}catch{}ta.remove();toast(ok?'已复制':'复制受限，请长按页面上的地址复制')}}
function mapURL(id){const p=TRIP.places[id];return 'https://uri.amap.com/search?'+new URLSearchParams({keyword:p.name+' '+p.address,city:p.city,view:'list',src:'chaoshan-pocket',callnative:'1'})}
function placeActions(id){const p=TRIP.places[id];if(!p)return '';return `<div class="actions"><a href="${esc(mapURL(id))}" target="_blank" rel="noopener">地图 · ${esc(p.short||p.name)} ↗</a><button class="secondary" data-copy="${esc(p.name+' · '+p.address)}">复制地址</button></div>`}
function art(id){if(!imageTitles[id])return '';return `<figure class="art-card"><button class="art-button" data-image="${esc(id)}" aria-label="放大${esc(imageTitles[id])}"><img src="images/${esc(id)}-preview.webp?v=20261002-r5" width="560" height="840" alt="${esc(imageTitles[id])}，生成插画与路线示意" loading="lazy" decoding="async"><span class="zoom-label">点图放大 ＋</span></button><figcaption><strong>${esc(imageTitles[id])}</strong><span class="art-disclaimer">生成插画 / 路线示意，导航用真实地图</span><a href="images/${esc(id)}-original.png?v=20261002-r5" target="_blank" rel="noopener">打开原图 ↗</a><span> · 原图需联网</span></figcaption></figure>`}
function foot(){return `<footer class="page-foot">${esc(TRIP.version)} · 计划时刻依当天情况调整。<br>${esc(TRIP.metadata?.imageDisclaimer||'插画由内置 ImageGen 生成，建筑外观、菜品与地理比例仅作示意。导航请打开真实地图。')}<div class="actions"><a href="full-text.html" target="_blank" rel="noopener" class="secondary">完整文字 / 打印 ↗</a><a href="#gallery" class="secondary">路线图册</a><button data-action="offline">保存离线阅读</button></div><p class="tiny" id="offline-state">正文和插图可离线保存；导航、天气与商家页面需要联网。</p></footer>`}
function switcher(){return `<div class="branch-switch"><div class="segmented" role="group" aria-label="10月4日行程选择"><button data-branch="city" aria-pressed="${branch==='city'}">留汕头 · 轻松</button><button data-branch="island" aria-pressed="${branch==='island'}">入南澳 · 可选</button></div><p>同步切换10/4游览与10/5返程起点；此选择不代表住宿已订。</p></div>`}
function checklist(){const list=TRIP.checklist||[];return `<div class="checklist">${list.map(([k,v])=>`<label><input type="checkbox" data-check="${esc(k)}" ${memory.get(k)==='1'?'checked':''}><span>${esc(v)}</span></label>`).join('')}</div>`}
function todayActions(){return `<div class="actions essential-actions"><a href="#day3">打开 10/3 行程 →</a><a href="#stay?focus=parking" class="secondary">泊车</a><a href="#stay" class="secondary">住宿</a></div>`}
function overview(){const s=TRIP.summary||{},p=TRIP.places.wantingli;return `<section class="hero"><div><div class="kicker">POCKET ROADBOOK / OCT 03—05</div><h1>${esc(s.title||'潮汕后半程，慢慢走。')}</h1><p class="eyeline">10/3 汕头 → 10/4 两种走法 → 10/5 番禺</p><p>${esc(s.sub||dayData('day3').sub)}</p><div class="chip-row">${(s.chips||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>${todayActions()}</div></section>
<div class="section-title"><small>01 /</small><h2>日期 + 今日去哪</h2></div><div class="day-cards">${activeDays.map(k=>{const d=dayData(k);return `<a class="day-card" href="#${k}"><span class="date">10.${k.slice(-1)}</span><strong>${esc(d.title)}</strong><span>${esc(d.route?.slice(0,2).join(' → ')||dayName(k))} →</span></a>`}).join('')}</div>
${p?`<section class="card stay-status"><span class="state">10/3 住宿 · ${esc(p.status||'意向待订')}</span><h2>${esc(p.short||p.name)}</h2><p>${esc(s.stayLead||p.note)}</p>${placeActions('wantingli')}<div class="actions"><a href="#stay" class="secondary">住宿与停车资料 →</a></div></section>`:''}
<div class="section-title"><small>02 /</small><h2>10/4，先选一种走法</h2></div>${switcher()}<div class="card"><h3>${branch==='city'?'留汕头，少一次搬行李':'南澳住一晚，返程早一些'}</h3><p>${esc(branch==='city'?s.cityBranch:s.islandBranch)}</p><div class="actions"><a href="#day4">查看 10/4 安排 →</a><a href="#day5" class="secondary">查看对应返程 →</a></div></div>
${s.highlights?.length?`<div class="callout"><h3>这几天，记住这些</h3><ul class="notes">${s.highlights.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}
<div class="section-title"><small>03 /</small><h2>路线，放大看</h2></div><div class="overview-art">${art('overview')}</div><div class="section-title"><small>CHECK /</small><h2>出门前再确认</h2></div>${checklist()}<p class="tiny">勾选仅是当前设备的个人记事，不代表订单确认。</p><div class="actions"><a href="#history" class="secondary">查看已走过的 10/1–2 →</a></div>${foot()}`}
function day(k){const n=Number(k.slice(-1)),d=dayData(k),archived=n<3;if(!d)return overview();const dest=n===3?'wantingli':n===4?(branch==='city'?'smallpark':'bay'):(branch==='city'?'wantingli':'bay');return `<header class="title-block"><div class="kicker">${archived?'ARCHIVE · 已走行程':'DAY '+String(n).padStart(2,'0')} / ${esc(d.date)} ${esc(d.week)}</div><h1>${esc(d.title)}</h1><p class="sub">${esc(d.sub)}</p></header>${archived?`<div class="callout archival"><strong>这是10/1–2的原计划存档。</strong><p>${esc(TRIP.metadata?.historyNotice||"原计划存档，未逐项核对实际完成情况。后半程从10/3继续。")}</p><div class="actions"><a href="#day3">打开最新行程 →</a><a href="#history" class="secondary">回历史目录</a></div></div>`:''}${n>=4?switcher():''}
${!archived?`<div class="actions essential-actions day-essentials">${TRIP.places[dest]?`<a href="${esc(mapURL(dest))}" target="_blank" rel="noopener">${n===5?"起点地图":"地图"} · ${esc(TRIP.places[dest].short||TRIP.places[dest].name)} ↗</a>`:''}<a href="#stay?focus=parking" class="secondary">泊车</a><a href="#stay" class="secondary">住宿</a></div>`:''}
<div class="route-line" aria-label="当日路线顺序">${(d.route||[]).map((p,i)=>`${i?'<i aria-hidden="true">→</i>':''}<span>${esc(p)}</span>`).join('')}</div><p class="travel-note">${esc(d.travel)}。转场时间是规划余量，以当天导航与现场通行为准。</p>
<div class="day-layout"><ol class="timeline">${(d.events||[]).map(e=>`<li class="event ${e[3]==='休息'?'rest':''}"><time class="event-time">${esc(e[0])}</time><article class="event-card"><span class="event-tag">${esc(e[3])}</span><h3>${esc(e[1])}</h3><p>${esc(e[2])}</p>${e[4]?placeActions(e[4]):''}</article></li>`).join('')}</ol><aside class="day-art">${art(d.image)}<p class="image-note">点图进入全屏；双指缩放、双击与拖动均可，右上关闭后回到原位置。</p><div class="callout"><h3>今天的重点</h3><p>${esc(d.highlight)}</p></div></aside></div>
<div class="below-day"><section class="callout warm"><h3>遇到雨 / 临时变化</h3><p>${esc(d.weather)}</p><a class="source-link" target="_blank" rel="noopener" href="https://www.weather.com.cn/weather/101280501.shtml">查看最新天气 ↗</a></section><section class="callout"><h3>${n===5?'回家与还车':'今晚住哪里'}</h3><p>${esc(d.sleep)}</p>${d.sleepId?placeActions(d.sleepId):''}</section></div><ul class="notes">${(d.notes||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><nav class="day-pager" aria-label="上一天和下一天"><a href="#${n<=3?(archived?'history':'overview'):'day'+(n-1)}">← ${n<=3?(archived?'历史目录':'总览'):'10月'+(n-1)+'日'}</a><a href="#${n===5?'stay':n===2?'history':'day'+(n+1)}">${n===5?'住宿与泊车':n===2?'历史目录':'10月'+(n+1)+'日'} →</a></nav>${foot()}`}
function placeCard(id){const p=TRIP.places[id];if(!p)return '';return `<article class="place-card" data-place="${esc(id)}"><span class="type">${esc(p.type)} / ${esc(p.city)}</span>${p.status?`<span class="state">${esc(p.status)}</span>`:''}<h3>${esc(p.name)}</h3><p class="address">${esc(p.address)}</p><p>${esc(p.note)}</p>${placeActions(id)}${p.source?`<a class="source-link" href="${esc(p.source)}" target="_blank" rel="noopener">资料来源 / 查看详情 ↗</a>`:''}</article>`}
const foodIds=(TRIP.foodIds||Object.keys(TRIP.places).filter(id=>TRIP.places[id].type!=='住宿')).filter(id=>TRIP.places[id]);
function placeResults(ids){const current=ids.filter(id=>TRIP.places[id].city!=='潮州'),historical=ids.filter(id=>TRIP.places[id].city==='潮州');return (current.length?current.map(placeCard).join(''):'')+(historical.length?`<details class="history-places"><summary>10/1–2 潮州地点存档 · ${historical.length}处</summary><div class="place-grid">${historical.map(placeCard).join('')}</div></details>`:'')||'<p class="empty">没有匹配地点，试试“汕头”或“火锅”。</p>'}
function food(){return `<header class="title-block"><div class="kicker">EAT & WALK / CHAOSHAN</div><h1>吃一顿，走一小段。</h1><p class="sub">后半程的美食与地点，地图按钮可直接找到地址。</p></header><div class="mini-art">${art('food')}<div><h3>同一区域，<br>顺路吃就好。</h3><p>餐饮是候选；国庆营业、等位与座位以当天为准，排队过久就换。</p></div></div><div class="search-wrap"><label for="place-search">找餐厅、景点、城市或地址</label><input id="place-search" type="search" placeholder="试试：汕头、小公园、牛肉…" autocomplete="off"></div><div class="place-grid" id="place-list">${placeResults(foodIds)}</div><p class="tiny">打开地图后，核对名称、分店与地址再导航。微信内可复制地址到地图 App。</p>${foot()}`}
function parking(){const p=TRIP.parking||{};return `<section id="parking" class="parking-section"><div class="section-title"><small>PARK /</small><h2>${esc(p.title||'车停好，再慢慢逛')}</h2></div><p>${esc(p.lead)}</p><div class="parking-grid"><div class="card"><ol class="notes parking-steps">${(p.steps||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol>${p.restriction?`<div class="callout warm"><p>${esc(p.restriction)}</p></div>`:''}${(p.placeIds||[]).map(placeActions).join('')}${p.sources?.length?`<details class="sources"><summary>停车资料来源</summary><ul>${p.sources.map(([n,u])=>`<li><a href="${esc(u)}" target="_blank" rel="noopener">${esc(n)} ↗</a></li>`).join('')}</ul></details>`:''}</div>${art('parking')}</div></section>`}
function stay(){return `<header class="title-block"><div class="kicker">STAY & PARK / OCT 03—05</div><h1>今晚住哪，车停哪里。</h1><p class="sub">望亭里是意向酒店，价格、余房与停车安排尚待确认。</p></header><div class="place-grid">${(TRIP.stayIds||['wantingli','yorman']).filter(id=>id!=='orange').map(placeCard).join('')}</div><div class="callout warm"><h3>先把房间落实</h3>${(TRIP.stayNotes||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</div>${switcher()}<div class="actions"><a href="#day4">10/4 两种走法 →</a><a href="#day5" class="secondary">对应返程 →</a></div>${parking()}<div class="section-title"><small>CHECK /</small><h2>实际要确认的事</h2></div>${checklist()}<p class="tiny">勾选是个人记事，不是代订。</p><details class="sources"><summary>10/1–2 已住酒店 · 历史记录</summary>${placeCard('orange')}<div class="actions"><a href="#history">查看已走行程 →</a></div></details><details class="sources"><summary>资料来源与核验范围</summary><p class="tiny">房态、目标日期价格、餐饮营业与停车空位需当天确认。地图车程与计划时刻会随路况变化。</p><ul>${(TRIP.sources||[]).map(([n,u])=>`<li><a href="${esc(u)}" target="_blank" rel="noopener">${esc(n)} ↗</a></li>`).join('')}</ul></details><details class="sources"><summary>手机怎么用：图片、离线与收藏</summary><ul class="notes"><li>顶部选10/3、4、5；10/1–2在“已走”入口。</li><li>点图片全屏查看，双指缩放、双击、拖动或用＋/−；“打开原图”可单独看大图。</li><li>右上关闭或浏览器返回可退出图片并回到原阅读位置。</li><li>分享按钮复制当前日期与分支链接；浏览器菜单可加到主屏幕或书签。</li><li>联网时点“保存离线阅读”，成功后可看正文与插图；系统可能清理缓存。地图、天气与商家页面仍需联网。</li></ul></details>${foot()}`}
function historyPage(){return `<header class="title-block"><div class="kicker">ARCHIVE / OCT 01—02</div><h1>已经走过的两天。</h1><p class="sub">${esc(TRIP.metadata?.historyNotice||"潮州段留作原计划存档；接下来的安排从10/3开始。")}</p></header><div class="day-cards archive-cards">${['day1','day2'].map(k=>{const d=TRIP.days[k];return `<a href="#${k}" class="day-card"><span class="date">10.${k.slice(-1)}</span><strong>${esc(d.title)}</strong><span>已走行程 · 查看存档 →</span></a>`}).join('')}</div><div class="callout"><h3>后半程从这里继续</h3><p>${esc(TRIP.summary?.sub)}</p>${todayActions()}</div>${foot()}`}
function gallery(){const ids=['overview','day3','day4city','day4island','day5','parking','food'].filter(k=>TRIP.images[k]);return `<header class="title-block"><div class="kicker">ILLUSTRATED GUIDE / IMAGEGEN</div><h1>随身路线图册。</h1><p class="sub">生成插画 / 路线示意，导航用真实地图。点图全屏，原图可以单独打开。</p></header><div class="gallery-grid">${ids.map(art).join('')}</div>${foot()}`}
function parseHash(){const hash=location.hash.slice(1)||'overview';const [p,q='']=hash.split('?');return {page:/^(overview|day[1-5]|food|stay|history|gallery)$/.test(p)?p:'overview',args:new URLSearchParams(q)}}
let renderedBranch='';
function render(){const r=parseHash();if(r.args.has('branch')&&['city','island'].includes(r.args.get('branch'))){branch=r.args.get('branch');memory.set('branch',branch)}
 const changed=r.page!==pageKey,rerender=changed||renderedBranch!==branch;
 if(rerender){if($('#viewer').open)hideViewer();pageKey=r.page;renderedBranch=branch;$('#content').innerHTML=pageKey==='overview'?overview():pageKey==='food'?food():pageKey==='stay'?stay():pageKey==='history'?historyPage():pageKey==='gallery'?gallery():day(pageKey);if(activeDays.includes(pageKey))lastDay=pageKey;
 $$('[data-day]').forEach(a=>{const active=a.dataset.day===pageKey||(a.dataset.day==='history'&&['day1','day2'].includes(pageKey));a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
 const section=pageKey.startsWith('day')?'day':['gallery','history'].includes(pageKey)?'overview':pageKey;$$('[data-section]').forEach(a=>{if(a.dataset.section===section)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('#bottom-day').href='#'+lastDay;
 $$('.desktop-nav>a').forEach(a=>{if(a.hash==='#'+(section==='day'?'day3':pageKey))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
 document.title=(pageKey.startsWith('day')?'10月'+pageKey.slice(-1)+'日 · ':pageKey==='food'?'美食与地点 · ':pageKey==='stay'?'住宿与泊车 · ':pageKey==='history'?'历史行程 · ':pageKey==='gallery'?'路线图册 · ':'')+'潮汕后半程 · 随身路书';
 if(changed)window.scrollTo({top:0,behavior:'instant'});
 }
 const id=r.args.get('image');if(id&&imageTitles[id]){if(!$('#viewer').open||currentImage!==id)showViewer(id)}else if($('#viewer').open)hideViewer();
 if(r.page==='stay'&&r.args.get('focus')==='parking'&&!id)requestAnimationFrame(()=>$('#parking')?.scrollIntoView({block:'start',behavior:'instant'}));
}
function setBranch(value){branch=value;memory.set('branch',value);const r=parseHash();r.args.set('branch',value);r.args.delete('image');history.replaceState(null,'','#'+r.page+'?'+r.args);render()}
$('#content').addEventListener('input',e=>{if(e.target.id==='place-search'){const q=e.target.value.trim().toLowerCase();const ids=foodIds.filter(id=>Object.values(TRIP.places[id]).join(' ').toLowerCase().includes(q));$('#place-list').innerHTML=placeResults(ids)}});
document.addEventListener('change',e=>{if(e.target.dataset.check)memory.set(e.target.dataset.check,e.target.checked?'1':'0')});
document.addEventListener('click',e=>{const el=e.target.closest('[data-copy],[data-image],[data-branch],[data-action]');if(!el)return;if(el.dataset.copy)copy(el.dataset.copy);if(el.dataset.image){const r=parseHash();r.args.set('image',el.dataset.image);history.pushState({viewer:true},'','#'+r.page+'?'+r.args);render()}if(el.dataset.branch)setBranch(el.dataset.branch);if(el.dataset.action==='offline')saveOffline()});
$('#font-toggle').addEventListener('click',()=>{const on=document.body.classList.toggle('large-text');memory.set('large',on?'1':'0');$('#font-toggle').setAttribute('aria-pressed',String(on))});
$('#share-page').addEventListener('click',async()=>{const r=parseHash();r.args.delete('image');if(r.page==='day4'||r.page==='day5'||r.page==='overview')r.args.set('branch',branch);const url=location.href.split('#')[0]+'#'+r.page+(r.args.size?'?'+r.args:'');if(navigator.share){try{await navigator.share({title:document.title,url});return}catch(e){if(e.name==='AbortError')return}}copy(url)});
window.addEventListener('hashchange',render);window.addEventListener('popstate',render);
// Fullscreen image viewer: keep reading position and use browser history to close.
const viewer=$('#viewer'),stage=$('#image-stage'),zoomImage=$('#zoom-image');let currentImage='',scale=1,panX=0,panY=0,baseW=0,baseH=0,scrollBefore=0,focusBefore=null;
let points=new Map(),gesture=null,lastTap=0,moved=false;
function sizeImage(){const w=zoomImage.naturalWidth||1024,h=zoomImage.naturalHeight||1536;const fit=Math.min((stage.clientWidth-16)/w,(stage.clientHeight-16)/h);baseW=w*fit;baseH=h*fit;zoomImage.style.width=baseW+'px';zoomImage.style.height=baseH+'px';applyTransform()}
function applyTransform(){const maxX=Math.max(0,(baseW*scale-stage.clientWidth)/2),maxY=Math.max(0,(baseH*scale-stage.clientHeight)/2);panX=Math.max(-maxX,Math.min(maxX,panX));panY=Math.max(-maxY,Math.min(maxY,panY));zoomImage.style.transform=`translate(${panX-baseW*scale/2}px,${panY-baseH*scale/2}px) scale(${scale})`;$('#zoom-value').value=Math.round(scale*100)+'%';$('#zoom-out').disabled=scale<=1;$('#zoom-in').disabled=scale>=6}
function setZoom(next,anchorX=0,anchorY=0){const prev=scale;scale=Math.max(1,Math.min(6,next));panX=anchorX-(anchorX-panX)*scale/prev;panY=anchorY-(anchorY-panY)*scale/prev;applyTransform()}
function resetZoom(){scale=1;panX=0;panY=0;applyTransform()}
function showViewer(id){currentImage=id;focusBefore=document.activeElement;scrollBefore=window.scrollY;$('#viewer-title').textContent=imageTitles[id];zoomImage.alt=imageTitles[id]+'，AI路线示意图';$('#image-original').href='images/'+id+'-original.png?v=20261002-r5';zoomImage.onload=()=>{resetZoom();sizeImage()};zoomImage.src='images/'+id+'.webp?v=20261002-r5';viewer.showModal();document.body.style.position='fixed';document.body.style.top=-scrollBefore+'px';document.body.style.width='100%';document.body.style.overflow='hidden';points.clear();gesture=null;scale=1;panX=panY=0;requestAnimationFrame(sizeImage);$('#viewer-close').focus()}
function hideViewer(){viewer.close();document.body.style.position='';document.body.style.top='';document.body.style.width='';document.body.style.overflow='';window.scrollTo(0,scrollBefore);points.clear();gesture=null;if(focusBefore?.isConnected)focusBefore.focus({preventScroll:true})}
function closeViewer(){if(history.state?.viewer)history.back();else{const r=parseHash();r.args.delete('image');history.replaceState(null,'','#'+r.page+(r.args.size?'?'+r.args:''));render()}}
$('#viewer-close').addEventListener('click',closeViewer);viewer.addEventListener('cancel',e=>{e.preventDefault();closeViewer()});$('#zoom-in').addEventListener('click',()=>setZoom(scale*1.4));$('#zoom-out').addEventListener('click',()=>setZoom(scale/1.4));$('#zoom-reset').addEventListener('click',resetZoom);
viewer.addEventListener('keydown',e=>{if(e.key==='+'||e.key==='='){e.preventDefault();setZoom(scale*1.4)}if(e.key==='-'){e.preventDefault();setZoom(scale/1.4)}if(e.key==='0')resetZoom()});
function localPoint(e){const r=stage.getBoundingClientRect();return {x:e.clientX-r.left-r.width/2,y:e.clientY-r.top-r.height/2}}
function startGesture(){const ps=[...points.values()];if(ps.length===2){gesture={type:'pinch',dist:Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y),cx:(ps[0].x+ps[1].x)/2,cy:(ps[0].y+ps[1].y)/2,scale,px:panX,py:panY};moved=true}else if(ps.length===1)gesture={type:'pan',x:ps[0].x,y:ps[0].y,px:panX,py:panY}}
stage.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;stage.setPointerCapture(e.pointerId);points.set(e.pointerId,localPoint(e));if(points.size===1)moved=false;startGesture()});
stage.addEventListener('pointermove',e=>{if(!points.has(e.pointerId)||!gesture)return;points.set(e.pointerId,localPoint(e));const ps=[...points.values()];if(gesture.type==='pinch'&&ps.length===2){const dist=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y),cx=(ps[0].x+ps[1].x)/2,cy=(ps[0].y+ps[1].y)/2;scale=Math.max(1,Math.min(6,gesture.scale*dist/Math.max(gesture.dist,1)));panX=cx-(gesture.cx-gesture.px)*scale/gesture.scale;panY=cy-(gesture.cy-gesture.py)*scale/gesture.scale;applyTransform()}else if(gesture.type==='pan'&&ps.length===1){const dx=ps[0].x-gesture.x,dy=ps[0].y-gesture.y;if(Math.hypot(dx,dy)>5)moved=true;panX=gesture.px+dx;panY=gesture.py+dy;applyTransform()}});
function endPointer(e){if(!points.has(e.pointerId))return;const p=points.get(e.pointerId);if(points.size===1&&!moved&&e.type==='pointerup'){const now=Date.now();if(now-lastTap<320){scale>1?resetZoom():setZoom(2.5,p.x,p.y);lastTap=0}else lastTap=now}points.delete(e.pointerId);if(points.size)startGesture();else gesture=null}
stage.addEventListener('pointerup',endPointer);stage.addEventListener('pointercancel',endPointer);stage.addEventListener('wheel',e=>{e.preventDefault();const p=localPoint(e);setZoom(scale*Math.exp(-e.deltaY*.002),p.x,p.y)},{passive:false});window.addEventListener('resize',()=>{if(viewer.open)sizeImage()});
// Optional offline pack stays within this site's scope. No external pages are cached.
let saving=false,workerReady=null;
if('serviceWorker' in navigator&&/^https?:$/.test(location.protocol)){workerReady=navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).catch(()=>null)}
async function saveOffline(){if(saving)return;if(!workerReady||!('caches' in window)){toast('此浏览器不支持离线保存，可打开完整文字版保存');return}saving=true;const buttons=$$('[data-action="offline"]');buttons.forEach(b=>{b.disabled=true;b.textContent='正在保存…'});try{const ready=await Promise.race([workerReady,new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),15000))]);if(!ready)throw new Error('worker');const meta=await fetch('offline-manifest.json',{cache:'no-store'}).then(r=>r.json());const cache=await caches.open(meta.cache);for(let i=0;i<meta.files.length;i++){const response=await fetch(meta.files[i],{cache:'reload'});if(!response.ok)throw new Error('fetch');await cache.put(new URL(meta.files[i],location.href).href,response);buttons.forEach(b=>b.textContent=`保存 ${i+1}/${meta.files.length}`)}memory.set('offline',TRIP.version);toast('离线保存完成：正文和路线插图已就绪');const s=$('#offline-state');if(s)s.textContent='已保存此版正文和插图；地图、天气、票务仍需联网。'}catch{toast('未能完整保存，请保持网络后再试；也可保存文字版')}finally{saving=false;buttons.forEach(b=>{b.disabled=false;b.textContent='保存离线阅读'})}}
render();
