'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const memory={get(k,d=''){try{return localStorage.getItem('cz-'+k)||d}catch{return d}},set(k,v){try{localStorage.setItem('cz-'+k,v)}catch{}}};
let branch=memory.get('branch','city'),pageKey='',lastDay='day1',toastTimer;
if(!['city','island'].includes(branch))branch='city';
const dayNames=['抵达','古城与桥','宅院与茶','慢城 / 海湾','回家'];
$('#day-nav').innerHTML=dayNames.map((n,i)=>`<a href="#day${i+1}" data-day="day${i+1}"><b>10.${i+1}</b>${n}</a>`).join('');
document.body.classList.toggle('large-text',memory.get('large')==='1');
$('#font-toggle').setAttribute('aria-pressed',String(document.body.classList.contains('large-text')));
function toast(s){clearTimeout(toastTimer);$('#toast').textContent=s;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
async function copy(s){try{await navigator.clipboard.writeText(s);toast('已复制')}catch{const ta=document.createElement('textarea');ta.value=s;ta.style.cssText='position:fixed;left:0;top:0;opacity:0';document.body.append(ta);ta.select();let ok=false;try{ok=document.execCommand('copy')}catch{}ta.remove();toast(ok?'已复制':'复制受限，请长按页面上的地址复制')}}
function mapURL(id){const p=TRIP.places[id];return 'https://uri.amap.com/search?'+new URLSearchParams({keyword:p.name,city:p.city,view:'list',src:'chaozhou-pocket',callnative:'1'})}
function placeActions(id){const p=TRIP.places[id];return `<div class="actions"><a href="${esc(mapURL(id))}" target="_blank" rel="noopener">高德找${esc(p.short)} ↗</a><button class="secondary" data-copy="${esc(p.name+' · '+p.address)}">复制地址</button></div>`}
function art(id){return `<figure class="art-card"><button class="art-button" data-image="${id}" aria-label="放大${esc(TRIP.images[id])}"><img src="images/${id}-preview.webp" width="560" height="840" alt="${esc(TRIP.images[id])}：AI示意路线与计划时间" loading="lazy" decoding="async"><span class="zoom-label">点图放大 ＋</span></button><figcaption><span>${esc(TRIP.images[id])}</span><span> · 可双指缩放</span></figcaption></figure>`}
function foot(){return `<footer class="page-foot">${esc(TRIP.version)} · 计划时刻依当天情况调整。<br>插画为内置 ImageGen 生成的路线示意；建筑外观、菜品摆盘与地理比例仅作插画参考。请用地点卡打开实际地图。<div class="actions"><a href="full-text.html" target="_blank" rel="noopener" class="secondary">完整文字 / 打印 ↗</a><button data-action="offline">保存离线阅读</button></div><p class="tiny" id="offline-state">正文和插图可离线保存；导航、天气、票务需要联网。</p></footer>`}
function switcher(){return `<div class="branch-switch"><div class="segmented" role="group" aria-label="10月4日行程选择"><button data-branch="city" aria-pressed="${branch==='city'}">留潮州 · 轻松</button><button data-branch="island" aria-pressed="${branch==='island'}">青澳湾 · 可选</button></div><p>同时切换10/4与10/5安排。选择只保存在这台设备，不代表已预订。</p></div>`}
function overview(){return `<section class="hero"><div><div class="kicker">ONE CITY, A SLOW HOLIDAY</div><h1>一城慢住，<br>一晚听海。</h1><p class="eyeline">吃好 · 睡好 · 慢慢在一起</p><p>潮州为主，南澳可选。<br>每天两小段外出，中间回房午休。</p><div class="chip-row"><span class="chip">一家三口</span><span class="chip">自驾 5 天</span><span class="chip">前两晚酒店已订</span></div></div>${art('overview')}</section>
<div class="section-title"><small>01 /</small><h2>今天，打开哪一天？</h2></div><div class="day-cards">${dayNames.map((n,i)=>`<a class="day-card" href="#day${i+1}"><span class="date">10.${i+1}</span><strong>${n}</strong><span>${['抵达安顿','梭船 · 卤鹅','工夫茶 · 甜品','一个分支','返程优先'][i]} →</span></a>`).join('')}</div>
<div class="callout"><h3>三个值得记住的瞬间</h3><p>广济桥的梭船开启，一小场工夫茶演出，一顿牛肉火锅。天气合适，再给青澳湾留一个清晨。</p></div>
<div class="split"><section class="card"><span class="state">已落实 · 10/1、10/2两晚</span><h3>桔子酒店 · 古城牌坊街店</h3><p>环城西路34号华侨大厦。高级大床，两晚共 <strong>¥1,737</strong>，10/3退房。</p>${placeActions('orange')}</section><section class="card"><span class="state">尚待落实 · 10/3、10/4</span><h3>先续10/3，再选10/4</h3><p>优先原店续住，减少搬行李。海边房间、三人总价与退改合适，再启用南澳。</p><div class="actions"><a href="#stay">查看住宿安排 →</a></div></section></div>
<div class="section-title"><small>02 /</small><h2>第四晚，留一个选择</h2></div>${switcher()}<div class="card"><h3>${branch==='city'?'继续住潮州':'青澳湾住一晚'}</h3><p>${branch==='city'?'西湖短走、午休、喝茶或补一个体验。10/5 09:00目标从潮州出发，直接回番禺。':'已有10/4 14:00–18:00入岛预约；仍须落实房间并核天气交通。只逛青澳湾，10/5 08:00目标出发返程。'}</p><div class="actions"><a href="#day4">打开这天的详细安排 →</a></div></div>
<div class="section-title"><small>03 /</small><h2>出门前，只剩三件事</h2></div>${checklist()}<p class="tiny">勾选仅供自己记事，不代表平台订单确认。</p>${foot()}`}
function checklist(){const list=[['night3','落实10/3住宿；能续原店最好'],['night4','决定10/4留潮州或住青澳湾，并落实该晚房间'],['tea','确认是否买载阳茶馆三人票；无位可以跳过']];return `<div class="checklist">${list.map(([k,v])=>`<label><input type="checkbox" data-check="${k}" ${memory.get(k)==='1'?'checked':''}><span>${v}</span></label>`).join('')}</div>`}
function day(k){const n=Number(k.slice(-1)),d=TRIP.days[k+(n>=4?branch:'')];return `<header class="title-block"><div class="kicker">DAY ${String(n).padStart(2,'0')} / ${d.date} ${d.week}</div><h1>${d.title}</h1><p class="sub">${d.sub}</p></header>${n>=4?switcher():''}<div class="route-line" aria-label="当日路线顺序">${d.route.map((p,i)=>`${i?'<i aria-hidden="true">→</i>':''}<span>${esc(p)}</span>`).join('')}</div><p class="travel-note">${d.travel}。转场时间为规划余量，以现场通行和导航为准。</p>
<div class="day-layout"><ol class="timeline">${d.events.map(e=>`<li class="event ${e[3]==='休息'?'rest':''}"><time class="event-time">${esc(e[0])}</time><article class="event-card"><span class="event-tag">${esc(e[3])}</span><h3>${esc(e[1])}</h3><p>${esc(e[2])}</p>${e[4]?placeActions(e[4]):''}</article></li>`).join('')}</ol><aside class="day-art">${art(d.image)}<p class="image-note">点图进入全屏查看。支持按钮、双指与双击缩放；关闭后回到这里。地图表现游览顺序，不按实际比例。</p><div class="callout"><h3>今天的记忆点</h3><p>${d.highlight}</p></div></aside></div>
<div class="below-day"><section class="callout warm"><h3>遇到雨 / 临时变化</h3><p>${d.weather}</p><a class="source-link" target="_blank" rel="noopener" href="https://www.weather.com.cn/textFC/hn.shtml">查看最新天气 ↗</a></section><section class="callout"><h3>今晚住哪里</h3><p>${d.sleep}</p>${d.sleepId?placeActions(d.sleepId):'<p>10/6 09:00前按约上门还车。</p>'}</section></div><ul class="notes">${d.notes.map(x=>`<li>${x}</li>`).join('')}</ul><nav class="day-pager" aria-label="上一天和下一天"><a href="#${n===1?'overview':'day'+(n-1)}">← ${n===1?'总览':'10月'+(n-1)+'日'}</a><a href="#${n===5?'stay':'day'+(n+1)}">${n===5?'住宿与准备':'10月'+(n+1)+'日'} →</a></nav>${foot()}`}
function placeCard(id){const p=TRIP.places[id];return `<article class="place-card"><span class="type">${esc(p.type)} / ${esc(p.city)}</span><h3>${esc(p.name)}</h3><p class="address">${esc(p.address)}</p><p>${esc(p.note)}</p>${placeActions(id)}${p.source?`<a class="source-link" href="${esc(p.source)}" target="_blank" rel="noopener">资料来源 / 查看详情 ↗</a>`:''}</article>`}
const foodIds=['abin','guantang','goose','veggie','sweet','breakfast','tea','kaiyuan','paifang','bridge','xu','westlake','bay','gate'];
function food(){return `<header class="title-block"><div class="kicker">EAT, WALK & TEA</div><h1>吃什么，去哪里。</h1><p class="sub">记住分店和地址，把排队时间留给家人。</p></header><div class="mini-art">${art('food')}<div><h3>火锅只选一顿，<br>点心三人分享。</h3><p>排队约30分钟仍无望入座，就换同片选择。各店国庆营业与座位未确认。</p></div></div><div class="search-wrap"><label for="place-search">找餐厅、景点或地址</label><input id="place-search" type="search" placeholder="试试：火锅、茶馆、西马路…" autocomplete="off"></div><div class="place-grid" id="place-list">${foodIds.map(placeCard).join('')}</div><p class="tiny">高德按钮打开地点搜索；请核对分店与地址后开始导航。微信内若无法调起地图，可复制地址到地图 App。</p>${foot()}`}
function stay(){return `<header class="title-block"><div class="kicker">SLEEP WELL, TRAVEL LIGHT</div><h1>先住舒服，再慢慢走。</h1><p class="sub">只有前两晚已订。后续房间、茶馆都不假装已经落实。</p></header>
<div class="place-grid">${placeCard('orange')}${placeCard('yorman')}</div>
<div class="callout warm"><h3>10/3、10/4住宿怎么补</h3><p><strong>先补10/3：</strong>原订房渠道看桔子高级大床一晚，优先连住。价格、余房、能否原房续住尚未确认。</p><p><strong>再定10/4：</strong>默认继续潮州；想去青澳湾，优先查悦缦，大床房可纳入选择。目标日一家三口完整价格、早餐、房型人数和退改需看订单。</p><p>原预算每晚一家¥500–1,000。平台日历起价不能当报价；“下单30分钟内免费取消”也不等于10/3晚上还能免费取消。</p></div>
<section class="card"><span class="state">南澳可选 · 不是必去</span><h3>10/4 14:00–18:00入岛预约</h3><p>用户已在“南澳畅行”完成私人车辆预约。按小程序最新核验位置与提示行驶，窗口不保证免排队。房间和天气不合适时，保留潮州计划即可。</p><div class="actions"><a href="#day4">看第4天两种安排 →</a></div><p class="tiny">预约截图、车牌、手机号与二维码未放入本公开网页。</p></section>
<div class="section-title"><small>CHECK /</small><h2>只剩三项实际决定</h2></div>${checklist()}<p class="tiny">勾选是当前设备上的记事功能，不是代订。</p>
<div class="split"><section class="card"><h3>出发与车上</h3><p>证件、订单、充电线、雨伞／轻雨衣、防滑鞋、防晒、水与简餐。取车核实油电、轮胎、雨刷、车机与租赁约定。</p><p>10/1 09:00番禺取车；10/5回广州；10/6 09:00前按约上门还车。每驾驶1.5–2小时休息。</p></section><section class="card"><h3>车宿这次怎么处理</h3><p>执行计划按酒店过夜。尚无确认允许三人SUV过夜的具体场地，交付车辆的睡面与驻车空调也未确认。</p><p>想看晨光可从青澳湾酒店步行出门。不能因为房间没订到，就自动改为路边车宿。</p></section></div>
<details class="sources"><summary>查看资料来源与核验边界</summary><p class="tiny">内容沿用9月30日收口研究，10月1日制作随身版时复核核心页面。房态、目标日餐厅营业、茶馆座位未获确认。天气不作实时保证，出发前看最新预警。</p><ul>${TRIP.sources.map(([n,u])=>`<li><a href="${esc(u)}" target="_blank" rel="noopener">${esc(n)} ↗</a></li>`).join('')}</ul><p class="tiny">车程约411/79公里为此前地图快照参考，节假日核验、拥堵、休息均会增加耗时。插画与正文的钟点均为计划。</p></details>
<details class="sources"><summary>手机怎么用：图片、离线与收藏</summary><ul class="notes"><li>顶部点日期，底部在总览、每天、吃与逛、住宿间切换。</li><li>点图放大；双指缩放、双击、拖动或用＋/−。右上“关闭”与手机返回键都能退出图片。</li><li>点“分享”复制当前日期链接。Safari/Chrome可在浏览器菜单添加到主屏幕或书签。</li><li>联网时点“保存离线阅读”，成功提示后可离线打开正文及8张插图。系统可能清理缓存；重要内容也可用完整文字版打印／保存。</li><li>地图、天气与订票链接需要联网；离线保存不会保存商家页面或实时库存。</li></ul></details>${foot()}`}
function parseHash(){const hash=location.hash.slice(1)||'overview';const [p,q='']=hash.split('?');return {page:/^(overview|day[1-5]|food|stay)$/.test(p)?p:'overview',args:new URLSearchParams(q)}}
let renderedBranch='';
function render(){const r=parseHash();if(r.args.has('branch')&&['city','island'].includes(r.args.get('branch'))){branch=r.args.get('branch');memory.set('branch',branch)}
  const changed=r.page!==pageKey,rerender=changed||renderedBranch!==branch;
  if(rerender){if($('#viewer').open)hideViewer();pageKey=r.page;renderedBranch=branch;$('#content').innerHTML=pageKey==='overview'?overview():pageKey==='food'?food():pageKey==='stay'?stay():day(pageKey);if(pageKey.startsWith('day'))lastDay=pageKey;
    $$('[data-day]').forEach(a=>{a.classList.toggle('active',a.dataset.day===pageKey);if(a.dataset.day===pageKey)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
    const section=pageKey.startsWith('day')?'day':pageKey;$$('[data-section]').forEach(a=>{if(a.dataset.section===section)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('#bottom-day').href='#'+lastDay;
    $$('.desktop-nav>a').forEach(a=>{if(a.hash==='#'+(section==='day'?'day1':section))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
    document.title=(pageKey.startsWith('day')?'10月'+pageKey.slice(-1)+'日 · ':pageKey==='food'?'吃与逛 · ':pageKey==='stay'?'住宿准备 · ':'')+'潮州慢假期';
    if(changed)window.scrollTo({top:0,behavior:'instant'});
  }
  const id=r.args.get('image');if(id&&TRIP.images[id]){if(!$('#viewer').open||currentImage!==id)showViewer(id)}else if($('#viewer').open)hideViewer();
}
function setBranch(value){branch=value;memory.set('branch',value);const r=parseHash();r.args.set('branch',value);r.args.delete('image');history.replaceState(null,'','#'+r.page+'?'+r.args);render()}
$('#content').addEventListener('input',e=>{if(e.target.id==='place-search'){const q=e.target.value.trim().toLowerCase();const ids=foodIds.filter(id=>Object.values(TRIP.places[id]).join(' ').toLowerCase().includes(q));$('#place-list').innerHTML=ids.length?ids.map(placeCard).join(''):'<p class="empty">没有匹配地点，试试“火锅”或“茶馆”。</p>'}});
document.addEventListener('change',e=>{if(e.target.dataset.check)memory.set(e.target.dataset.check,e.target.checked?'1':'0')});
document.addEventListener('click',e=>{const el=e.target.closest('[data-copy],[data-image],[data-branch],[data-action]');if(!el)return;if(el.dataset.copy)copy(el.dataset.copy);if(el.dataset.image){const r=parseHash();r.args.set('image',el.dataset.image);history.pushState({viewer:true},'','#'+r.page+'?'+r.args);render()}if(el.dataset.branch)setBranch(el.dataset.branch);if(el.dataset.action==='offline')saveOffline()});
$('#font-toggle').addEventListener('click',()=>{const on=document.body.classList.toggle('large-text');memory.set('large',on?'1':'0');$('#font-toggle').setAttribute('aria-pressed',String(on))});
$('#share-page').addEventListener('click',async()=>{const r=parseHash();r.args.delete('image');if(r.page==='day4'||r.page==='day5')r.args.set('branch',branch);const url=location.href.split('#')[0]+'#'+r.page+(r.args.size?'?'+r.args:'');if(navigator.share){try{await navigator.share({title:document.title,url});return}catch(e){if(e.name==='AbortError')return}}copy(url)});
window.addEventListener('hashchange',render);window.addEventListener('popstate',render);
// Fullscreen image viewer: keep reading position and use browser history to close.
const viewer=$('#viewer'),stage=$('#image-stage'),zoomImage=$('#zoom-image');let currentImage='',scale=1,panX=0,panY=0,baseW=0,baseH=0,scrollBefore=0,focusBefore=null;
let points=new Map(),gesture=null,lastTap=0,moved=false;
function sizeImage(){const w=zoomImage.naturalWidth||1024,h=zoomImage.naturalHeight||1536;const fit=Math.min((stage.clientWidth-16)/w,(stage.clientHeight-16)/h);baseW=w*fit;baseH=h*fit;zoomImage.style.width=baseW+'px';zoomImage.style.height=baseH+'px';applyTransform()}
function applyTransform(){const maxX=Math.max(0,(baseW*scale-stage.clientWidth)/2),maxY=Math.max(0,(baseH*scale-stage.clientHeight)/2);panX=Math.max(-maxX,Math.min(maxX,panX));panY=Math.max(-maxY,Math.min(maxY,panY));zoomImage.style.transform=`translate(${panX-baseW*scale/2}px,${panY-baseH*scale/2}px) scale(${scale})`;$('#zoom-value').value=Math.round(scale*100)+'%';$('#zoom-out').disabled=scale<=1;$('#zoom-in').disabled=scale>=6}
function setZoom(next,anchorX=0,anchorY=0){const prev=scale;scale=Math.max(1,Math.min(6,next));panX=anchorX-(anchorX-panX)*scale/prev;panY=anchorY-(anchorY-panY)*scale/prev;applyTransform()}
function resetZoom(){scale=1;panX=0;panY=0;applyTransform()}
function showViewer(id){currentImage=id;focusBefore=document.activeElement;scrollBefore=window.scrollY;$('#viewer-title').textContent=TRIP.images[id];zoomImage.alt=TRIP.images[id]+'，AI路线示意图';$('#image-original').href='images/'+id+'.webp';zoomImage.onload=()=>{resetZoom();sizeImage()};zoomImage.src='images/'+id+'.webp';viewer.showModal();document.body.style.position='fixed';document.body.style.top=-scrollBefore+'px';document.body.style.width='100%';document.body.style.overflow='hidden';points.clear();gesture=null;scale=1;panX=panY=0;requestAnimationFrame(sizeImage);$('#viewer-close').focus()}
function hideViewer(){viewer.close();document.body.style.position='';document.body.style.top='';document.body.style.width='';document.body.style.overflow='';window.scrollTo(0,scrollBefore);points.clear();gesture=null;if(focusBefore?.isConnected)focusBefore.focus({preventScroll:true})}
function closeViewer(){if(history.state?.viewer)history.back();else{const r=parseHash();r.args.delete('image');history.replaceState(null,'','#'+r.page+(r.args.size?'?'+r.args:''));render()}}
$('#viewer-close').addEventListener('click',closeViewer);viewer.addEventListener('cancel',e=>{e.preventDefault();closeViewer()});$('#zoom-in').addEventListener('click',()=>setZoom(scale*1.4));$('#zoom-out').addEventListener('click',()=>setZoom(scale/1.4));$('#zoom-reset').addEventListener('click',resetZoom);
viewer.addEventListener('keydown',e=>{if(e.key==='+'||e.key==='='){e.preventDefault();setZoom(scale*1.4)}if(e.key==='-'){e.preventDefault();setZoom(scale/1.4)}if(e.key==='0')resetZoom()});
function localPoint(e){const r=stage.getBoundingClientRect();return {x:e.clientX-r.left-r.width/2,y:e.clientY-r.top-r.height/2}}
function startGesture(){const ps=[...points.values()];if(ps.length===2){gesture={type:'pinch',dist:Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y),cx:(ps[0].x+ps[1].x)/2,cy:(ps[0].y+ps[1].y)/2,scale,px:panX,py:panY};moved=true}else if(ps.length===1)gesture={type:'pan',x:ps[0].x,y:ps[0].y,px:panX,py:panY}}
stage.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;stage.setPointerCapture(e.pointerId);points.set(e.pointerId,localPoint(e));if(points.size===1)moved=false;startGesture()});
stage.addEventListener('pointermove',e=>{if(!points.has(e.pointerId)||!gesture)return;points.set(e.pointerId,localPoint(e));const ps=[...points.values()];if(gesture.type==='pinch'&&ps.length===2){const dist=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y),cx=(ps[0].x+ps[1].x)/2,cy=(ps[0].y+ps[1].y)/2;scale=Math.max(1,Math.min(6,gesture.scale*dist/Math.max(gesture.dist,1)));panX=cx-(gesture.cx-gesture.px)*scale/gesture.scale;panY=cy-(gesture.cy-gesture.py)*scale/gesture.scale;applyTransform()}else if(gesture.type==='pan'&&ps.length===1){const dx=ps[0].x-gesture.x,dy=ps[0].y-gesture.y;if(Math.hypot(dx,dy)>5)moved=true;panX=gesture.px+dx;panY=gesture.py+dy;applyTransform()}});
function endPointer(e){if(!points.has(e.pointerId))return;const p=points.get(e.pointerId);if(points.size===1&&!moved&&e.type==='pointerup'){const now=Date.now();if(now-lastTap<320){scale>1?resetZoom():setZoom(2.5,p.x,p.y);lastTap=0}else lastTap=now}points.delete(e.pointerId);if(points.size)startGesture();else gesture=null}
stage.addEventListener('pointerup',endPointer);stage.addEventListener('pointercancel',endPointer);stage.addEventListener('wheel',e=>{e.preventDefault();const p=localPoint(e);setZoom(scale*Math.exp(-e.deltaY*.002),p.x,p.y)},{passive:false});window.addEventListener('resize',()=>{if(viewer.open)sizeImage()});
// Optional offline pack stays within this site's scope. No external pages are cached.
let saving=false,workerReady=null;
if('serviceWorker' in navigator&&/^https?:$/.test(location.protocol)){workerReady=navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).catch(()=>null)}
async function saveOffline(){if(saving)return;if(!workerReady||!('caches' in window)){toast('此浏览器不支持离线保存，可打开完整文字版保存');return}saving=true;const buttons=$$('[data-action="offline"]');buttons.forEach(b=>{b.disabled=true;b.textContent='正在保存…'});try{const ready=await Promise.race([workerReady,new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),15000))]);if(!ready)throw new Error('worker');const meta=await fetch('offline-manifest.json',{cache:'no-store'}).then(r=>r.json());const cache=await caches.open(meta.cache);for(let i=0;i<meta.files.length;i++){const response=await fetch(meta.files[i],{cache:'reload'});if(!response.ok)throw new Error('fetch');await cache.put(new URL(meta.files[i],location.href).href,response);buttons.forEach(b=>b.textContent=`保存 ${i+1}/${meta.files.length}`)}memory.set('offline',TRIP.version);toast('离线保存完成：正文和8张插图已就绪');const s=$('#offline-state');if(s)s.textContent='已保存此版正文和插图；地图、天气、票务仍需联网。'}catch{toast('未能完整保存，请保持网络后再试；也可保存文字版')}finally{saving=false;buttons.forEach(b=>{b.disabled=false;b.textContent='保存离线阅读'})}}
render();
